Sum of consecutive primes
---

The prime 41, can be written as the sum of six consecutive primes:
$$
41 = 2+3+5+7+11+13
$$

This is the longest sum of consecutive primes that adds to a prime below one-hundred.

The longest sum of consecutive primes below one-thousand that adds to a prime, contains 21 terms, and is equal to 953.

Which prime, below one-million, can be written as the sum of the most consecutive primes?

If it's not the 21 terms adding to 953, then it's a larger prime with more terms. So we only need to check consecutive prime sums greater than 21 terms.
The consecutive primes are also going to be "sort of" close together, so there's no need to add any that are much greater than 1 million / 21.

In [55]:
1e6 / 21

47619.04761904762

In [3]:
import numpy as np
import sympy as sp

In [58]:
sp.prime(6000)

59359

In [37]:
sp.prime(78499), sp.prime(78498)

(1000003, 999983)

The 78498th prime is the largest below 1 million.

The largest sum is probably near 1 million.

In [63]:
small_primes = list(sp.primerange(1,47000))

In [65]:
sum(small_primes[-22:])

1030756

The longest string can be found by adding up the smallest consecutive primes until one reaches 1 million.

In [66]:
string_length = 21
le_seumme = sum(small_primes[:string_length])
while le_seumme < 1e6:
    le_seumme = le_seumme + small_primes[string_length]
    string_length += 1
string_length, le_seumme

(547, 1001604)

In [85]:
sum(small_primes[:546])

997661

In [86]:
possible_length = 547
prime_not_found = True
while possible_length > 21 and prime_not_found:
    translation = 0
    possible_length -= 1
    print(f'checking lengths of {possible_length}')
    has_not_overflowed = True
    while possible_length + translation < len(small_primes) and has_not_overflowed and prime_not_found:
        print(f'translation {translation}')
        the_sum = sum(small_primes[translation: possible_length + translation])
        if sp.isprime(the_sum):
            prime_not_found = False
        elif the_sum > 1e6:
            has_not_overflowed = False
        else:
            translation += 1
the_sum

checking lengths of 546
translation 0
translation 1
checking lengths of 545
translation 0
translation 1
translation 2
checking lengths of 544
translation 0
translation 1
translation 2
translation 3
checking lengths of 543
translation 0
translation 1
translation 2
translation 3


997651

In [88]:
sp.isprime(997651)

True

In [89]:
translation

3

In [90]:
possible_length

543

In [92]:
sum(small_primes[3:543+3])

997651

The prime number is 997651, and it's the sum of these 543 consecutive prime numbers:

In [93]:
small_primes[3:543+3]

[7,
 11,
 13,
 17,
 19,
 23,
 29,
 31,
 37,
 41,
 43,
 47,
 53,
 59,
 61,
 67,
 71,
 73,
 79,
 83,
 89,
 97,
 101,
 103,
 107,
 109,
 113,
 127,
 131,
 137,
 139,
 149,
 151,
 157,
 163,
 167,
 173,
 179,
 181,
 191,
 193,
 197,
 199,
 211,
 223,
 227,
 229,
 233,
 239,
 241,
 251,
 257,
 263,
 269,
 271,
 277,
 281,
 283,
 293,
 307,
 311,
 313,
 317,
 331,
 337,
 347,
 349,
 353,
 359,
 367,
 373,
 379,
 383,
 389,
 397,
 401,
 409,
 419,
 421,
 431,
 433,
 439,
 443,
 449,
 457,
 461,
 463,
 467,
 479,
 487,
 491,
 499,
 503,
 509,
 521,
 523,
 541,
 547,
 557,
 563,
 569,
 571,
 577,
 587,
 593,
 599,
 601,
 607,
 613,
 617,
 619,
 631,
 641,
 643,
 647,
 653,
 659,
 661,
 673,
 677,
 683,
 691,
 701,
 709,
 719,
 727,
 733,
 739,
 743,
 751,
 757,
 761,
 769,
 773,
 787,
 797,
 809,
 811,
 821,
 823,
 827,
 829,
 839,
 853,
 857,
 859,
 863,
 877,
 881,
 883,
 887,
 907,
 911,
 919,
 929,
 937,
 941,
 947,
 953,
 967,
 971,
 977,
 983,
 991,
 997,
 1009,
 1013,
 1019,
 1021,
 1031